trainee_export/urls.py
from django.urls import path

from edc_dashboard import UrlConfig
from trainee_export.views.home_view import HomeView
from trainee_export.views.listboard_view import ListBoardView

from .patterns import export_identifier
from .admin_site import *

app_name = 'trainee_export'

urlpatterns = [
    path('admin/', trainee_export_admin.urls),
    path('', HomeView.as_view(), name='home_url'),
]



export_listboard_url_config = UrlConfig(
    url_name='export_listboard_url',
    view_class=ListBoardView,
    label='export_listboard',
    identifier_label='export_identifier',
    identifier_pattern=export_identifier)


urlpatterns += export_listboard_url_config.listboard_urls

trainee_export/models/__init.py
from .export_file import ExportFile

trainee_export/models/export.py
from django.contrib.sites.models import Site
from django.db import models

from edc_base.model_mixins import BaseUuidModel

from edc_base.sites import SiteModelMixin
from edc_search.model_mixins import SearchSlugManager
from edc_search.model_mixins import SearchSlugModelMixin as Base

from ..identifiers import ExportIdentifier


class ExportFileManager(SearchSlugManager, models.Manager):

    def get_by_natural_key(self, export_identifier):
        return self.get(export_identifier=export_identifier)


class SearchSlugModelMixin(Base):

    def get_search_slug_fields(self):
        fields = super().get_search_slug_fields()
        return fields

    class Meta:
        abstract = True


class ExportFile(SiteModelMixin, SearchSlugModelMixin, BaseUuidModel):

    identifier_cls = ExportIdentifier

    export_identifier = models.CharField(
        verbose_name="Export Identifier",
        max_length=36,
        unique=True,
        editable=False)

    site = models.ForeignKey(
        Site, on_delete=models.PROTECT,
        related_name='django_site', 
        null=True, editable=False)

    study = models.CharField(max_length=100, blank=True)

    description = models.CharField(max_length=255, blank=True)

    document = models.FileField(upload_to='documents/')

    uploaded_at = models.DateTimeField(auto_now_add=True)

    download_time = models.DecimalField(
        null=True,
        max_digits=10,
        decimal_places=2)

    download_complete = models.BooleanField(
        default=False,)

    def __str__(self):
        return f'{self.export_identifier}'

    def natural_key(self):
        return self.export_identifier

    def get_search_slug_fields(self):
        fields = super().get_search_slug_fields()
        fields.append('export_identifier')
        return fields

    @property
    def doc_url(self):
        """Return the file url.
        """
        try:
            return self.document.url
        except ValueError:
            return None

trainee_export/models/export_file.py
from django.contrib.sites.models import Site
from django.db import models

from edc_base.model_mixins import BaseUuidModel

from edc_base.sites import SiteModelMixin
from edc_search.model_mixins import SearchSlugManager
from edc_search.model_mixins import SearchSlugModelMixin as Base

from ..identifiers import ExportIdentifier


class ExportFileManager(SearchSlugManager, models.Manager):

    def get_by_natural_key(self, export_identifier):
        return self.get(export_identifier=export_identifier)


class SearchSlugModelMixin(Base):

    def get_search_slug_fields(self):
        fields = super().get_search_slug_fields()
        return fields

    class Meta:
        abstract = True


class ExportFile(SiteModelMixin, SearchSlugModelMixin, BaseUuidModel):

    identifier_cls = ExportIdentifier

    export_identifier = models.CharField(
        verbose_name="Export Identifier",
        max_length=36,
        unique=True,
        editable=False)

    site = models.ForeignKey(
        Site, on_delete=models.PROTECT,
        related_name='django_site', 
        null=True, editable=False)

    study = models.CharField(max_length=100, blank=True)

    description = models.CharField(max_length=255, blank=True)

    document = models.FileField(upload_to='documents/')

    uploaded_at = models.DateTimeField(auto_now_add=True)

    download_time = models.DecimalField(
        null=True,
        max_digits=10,
        decimal_places=2)

    download_complete = models.BooleanField(
        default=False,)

    def __str__(self):
        return f'{self.export_identifier}'

    def natural_key(self):
        return self.export_identifier

    def get_search_slug_fields(self):
        fields = super().get_search_slug_fields()
        fields.append('export_identifier')
        return fields

    @property
    def doc_url(self):
        """Return the file url.
        """
        try:
            return self.document.url
        except ValueError:
            return None
        

trainee_export/forms/__init.py
from .export_file_form import ExportFileForm

trainee_export/forms/export_file_form.py
from django import forms
from trainee_export.models.export_file import ExportFile


class ExportFileForm(forms.ModelForm):
    class Meta:
        model = ExportFile
        fields = ('description', 'document', )

trainee_export/views/__init.py
from .administration_view import AdministrationView
from .home_view import HomeView
from .listboard_view import ListBoardView

trainee_export/views/administration_view.py
from django.views.generic import TemplateView
from edc_base.view_mixins import AdministrationViewMixin
from edc_base.view_mixins import EdcBaseViewMixin


class AdministrationView(EdcBaseViewMixin,
                         AdministrationViewMixin, TemplateView):
    pass

trainee_export/views/home_view.py
import datetime
import re
import threading
import time

from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView
from edc_base.view_mixins import EdcBaseViewMixin
from edc_navbar import NavbarViewMixin
from trainee_export.views.listboard_view_mixin import ListBoardViewMixin
from trainee_export.models.export_file import ExportFile

from ..identifiers import ExportIdentifier



class HomeView(ListBoardViewMixin, EdcBaseViewMixin,
               NavbarViewMixin, TemplateView):

    template_name = 'trainee_export/home.html'
    navbar_name = 'trainee_export'
    navbar_selected_item = 'study_data_export'
    identifier_cls = ExportIdentifier

    def stop_main_thread(self, thread_name):
        """Stop export file generation thread.
        """
        time.sleep(20)
        threads = threading.enumerate()
        threads = [t for t in threads if t.is_alive()]
        for thread in threads:
            if thread.name == thread_name:
                thread._stop()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        download = self.request.GET.get('download')

        if download == '2':
            self.generate_export(thread_name='trainee_non_crf_export',
                                 thread_target=self.download_non_crf_data,
                                 description='Trainee Non CRF Export')
        elif download == '3':
            self.generate_export(thread_name='trainee_subject_crf_export',
                                 thread_target=self.download_subject_data,
                                 description='Trainee Subject CRF Export')
        non_crf_exports = ExportFile.objects.filter(
            description='Trainee Non CRF Export').order_by('-uploaded_at')[:10]
        subject_crf_exports = ExportFile.objects.filter(
            description='Trainee Subject CRF Export').order_by('-uploaded_at')[:10]
       
        #breakpoint()
        context.update(
            non_crf_exports=non_crf_exports,
            subject_crf_exports=subject_crf_exports,
            )
        return context

    def generate_export(self, thread_name=None, active_download=False,
                        thread_target=None, description=None):

        threads = threading.enumerate()

        if threads:
            for thread in threads:
                if thread.name == thread_name:
                    active_download = True
                    messages.add_message(
                        self.request, messages.INFO,
                        (f'Download for {description} that was initiated is still running '
                         'please wait until an export is fully prepared.'))

        if not active_download:
            is_clean = self.is_clean(description=description)
            if is_clean:

                #breakpoint()

                download_thread = threading.Thread(
                    name=thread_name, target=thread_target,
                    daemon=True)
                download_thread.start()
                last_doc = ExportFile.objects.filter(description=description,download_complete=True).order_by('created').last()

                if last_doc:
                    start_time = datetime.datetime.now().strftime(
                        "%d/%m/%Y %H:%M:%S")
                    last_doc_time = round(
                        float(last_doc.download_time) / 60.0, 2)

                    messages.add_message(
                        self.request, messages.INFO,
                        (f'Download for {description}has been initiated, you will receive an email once '
                         'the download is completed. Estimated download time: '
                         f'{last_doc_time} minutes, file generation started at:'
                         f' {start_time}'))
                else:
                    messages.add_message(
                        self.request, messages.INFO,
                        (f'Download for {description} initiated, you will receive an email once '
                         'the download is completed.'))
                    

        

trainee_export/views/listboard_view.py
import datetime
import re
import threading
import time

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.constants import LOOKUP_SEP
from django.utils.decorators import method_decorator

from edc_base.view_mixins import EdcBaseViewMixin
from edc_dashboard.view_mixins import ListboardFilterViewMixin, SearchFormViewMixin
from edc_dashboard.views import ListboardView
from edc_navbar import NavbarViewMixin
from trainee_export.models.export_file import ExportFile
from trainee_export.model_wrappers.export_file_model_wrapper import ExportFileModelWrapper

from ..identifiers import ExportIdentifier

from .listboard_view_mixin import ListBoardViewMixin


class ListBoardView(NavbarViewMixin, EdcBaseViewMixin, ListBoardViewMixin,
                    ListboardFilterViewMixin, SearchFormViewMixin, ListboardView):

    listboard_template = 'export_listboard_template'
    listboard_url = 'export_listboard_url'
    listboard_panel_style = 'info'
    listboard_fa_icon = "fa-user-plus"

    model = 'trainee_export.exportfile'
    model_wrapper_cls = ExportFileModelWrapper
    identifier_cls = ExportIdentifier
    navbar_name = 'trainee_export'
    navbar_selected_item = 'export_data'
    ordering = '-modified'
    paginate_by = 10
    search_form_url = 'export_listboard_url'
    description_queryset_lookups = []

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def stop_main_thread(self, thread_name):
        """Stop export file generation thread.
        """
        time.sleep(20)
        threads = threading.enumerate()
        threads = [t for t in threads if t.is_alive()]
        for thread in threads:
            if thread.name == thread_name:
                thread._stop()

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        download = self.request.GET.get('download')

        if download == '1':
            self.generate_export(thread_name='trainee_all_export',
                                 thread_target=self.download_all_data,
                                 description='Trainee All Export')
            
        context.update(export_add_url=self.model_cls().get_absolute_url())
        
        return context

    def generate_export(self, thread_name=None, active_download=False,
                        thread_target=None, description=None):

        threads = threading.enumerate()

        if threads:
            for thread in threads:
                if thread.name == thread_name:
                    active_download = True
                    messages.add_message(
                        self.request, messages.INFO,
                        (f'Download for {description} that was initiated is still running '
                         'please wait until an export is fully prepared.'))

        if not active_download:
            is_clean = self.is_clean(description=description)
            if is_clean:

                download_thread = threading.Thread(
                    name=thread_name, target=thread_target,
                    daemon=True)
                download_thread.start()
                last_doc = ExportFile.objects.filter(
                    description=description,
                    download_complete=True).order_by('created').last()

                if last_doc:
                    start_time = datetime.datetime.now().strftime(
                        "%d/%m/%Y %H:%M:%S")
                    last_doc_time = round(
                        float(last_doc.download_time) / 60.0, 2)

                    messages.add_message(
                        self.request, messages.INFO,
                        (f'Download for {description} has been initiated, you will receive an email once '
                         'the download is completed. Estimated download time: '
                         f'{last_doc_time} minutes, file generation started at:'
                         f' {start_time}'))
                else:
                    messages.add_message(
                        self.request, messages.INFO,
                        (f'Download for {description} initiated, you will receive an email once '
                         'the download is completed.'))

    def get_queryset_filter_options(self, request, *args, **kwargs):
        options = super().get_queryset_filter_options(request, *args, **kwargs)
        options = self.add_description_filter_options(
                options=options, **kwargs)
        if kwargs.get('export_identifier'):
            options.update(
                {'export_identifier': kwargs.get('export_identifier')})
        return options

    @property
    def description_lookup_prefix(self):
        description_lookup_prefix = LOOKUP_SEP.join(self.description_queryset_lookups)
        return f'{description_lookup_prefix}__' if description_lookup_prefix else ''

    def add_description_filter_options(self, options=None, **kwargs):
        """Updates the filter options to limit the description for all data
        download.
        """
        description = 'Trainee All Export'
        options.update(
            {f'{self.description_lookup_prefix}description': description})
        return options

    def extra_search_options(self, search_term):
        q = Q()
        if re.match('^[A-Z]+$', search_term):
            q = Q(first_name__exact=search_term)
        return q

trainee_export/templates/trainee_export/base.html
{% extends 'edc_base/base.html' %}

{% load static %}

{% block extra-scripts %}
{{ block.super }}
<script>

$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
    $("#success-alert").fadeTo(1000, 500).slideUp(500, function(){
        $("#success-alert").slideUp(500);
    });    
});

</script>
{% endblock extra-scripts %} 

{% block extra-styles %}
{{ block.super }}
<style>
  .panel-extended {
    min-height: 200px;
    overflow-y: scroll;
  }
  </style>
{% endblock %}



{% block topbar_navbar_extra_items %}

    {{ block.super }}
    {{ navbar.name }}

{% endblock topbar_navbar_extra_items %}


{% block modals %}

{{ block.super }}
    {% include 'trainee_export/help_modal.html' %}
{% endblock modals %}

trainee_export/templates/trainee_export/help_modal.html
<!-- Modal -->
<div id="helpModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
  
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Help</h4>
        </div>
        <div class="modal-body">
          <div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a role="button" href="#collapseIcons" data-toggle="collapse" data-parent="#accordion">Icon reference</a>
                </h4>
              </div>
              <div id="collapseIcons" class="panel-collapse collapse">
                <div class="panel-body">
                  <ul class="list-group">
                  <li class="list-group-item"><i class="fa fa-plus fa-lg"></i> Add</li>
                  <li class="list-group-item"><i class="fa fa-pencil-alt fa-lg"></i> Change</li>
                  <li class="list-group-item"><i class="fa fa-file-o fa-lg"></i> Report. </li>
                  <li class="list-group-item"><i class="fa fa-files-o fa-lg"></i> Reports.</li>
                  <li class="list-group-item"><i class="fa fa-history fa-lg"></i> Report history.</li>
                  <li class="list-group-item"><i class="fa fa-user-circle fa-lg"></i> Subject</li>
                  <li class="list-group-item"><i class="fa fa-male fa-lg"></i> Male</li>
                  <li class="list-group-item"><i class="fa fa-female fa-lg"></i> Female</li>
                  <li class="list-group-item"><i class="fa fa-search fa-lg"></i> Search</li>
                  <li class="list-group-item"><i class="fa fa-undo fa-lg"></i> Undo a search</li>
                  <li class="list-group-item"><i class="fa fa-filter fa-lg"></i> Filter a list</li>
                  <li class="list-group-item"><i class="fa fa-star fa-lg"></i> Complete</li>
                  <li class="list-group-item"><i class="fa fa-star-half-o fa-lg"></i> Incomplete</li>
                  <li class="list-group-item"><i class="fa fa-star-o fa-lg"></i> New</li>
                  <li class="list-group-item"><i class="fa fa-spinner fa-lg"></i> In progress</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
  
    </div>
  </div>

trainee_export/templates/trainee_export/home.html
{% extends 'edc_base/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block extra-scripts %}
	{{ block.super }}
	<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css">
	<script type="text/javascript">
	$(document).ready(function() {
	    $('#missing-crfs').DataTable({
	    	"ordering": false
	    });
	} );
	</script>

	<script type="text/javascript">

	  jQuery(function() {
	    jQuery('#users').change(function() {
	        this.form.submit();
	    });
	});
	</script>
{% endblock extra-scripts %}

{% block main %}
<div class="container">
   <div class="row">
    
    <p></p>
    <h1>Trainee data export</h1>
    <p>Generate and download study data sets from the tables below.</p>
    <p> </p><p> </p>
    
        <div class="col-md-10 col-md-offset-1">

			{% include "trainee_export/non_crf_export.html" %}            
            {% include "trainee_export/subject_crf_export.html" %}

		</div>
	</div>
</div>
{% endblock main %}

trainee_export/templates/trainee_export/listboard.html
{% extends "edc_dashboard/listboard.html" %}
{% load admin_urls %}
{% load edc_base_extras %}

{% block extra-scripts %}
{{ block.super }}

<script type="text/javascript">
</script>
{% endblock extra-scripts %}
             
{% block listboard_panel %}
    <a id="download_td_files" title="Generate all Export" class="btn btn-sm btn-default" role="button" 
        href="{{ export_listboard_url }}?download=1">
            <i class="fa fa-plus fa-sm"></i> Generate Trainee Export
    </a>
    <a id="return_to_home" title="go back" class="btn btn-sm btn-default" role="button" 
        href="/">
            <i class="fa fa-arrow-left fa-sm"></i> Go Back
    </a>

{% endblock listboard_panel %}

{% block listboard_table_button_column %}
{% endblock listboard_table_button_column %}

{% block listboard_table_header %}
    <!-- begin results header -->
    <th>#</th>
    <th>Export Identifier</th>
    <th>Description</th>
    <th>study</th>
    <th>Download Export</th>
    <th>Uploaded Date</th>
    <th>Estimated File Preparation Time (Minutes)</th>
    <th>User</th>
    <!-- end results header -->
{% endblock listboard_table_header %}


{% block listboard_table_columns %}
	<td>{{ result.export_identifier }} </td>
	<td>{{ result.description }} </td>
	<td>{{ result.study }} </td>
	<td>{% if result.file_url %}
	   <a href={{ result.file_url }}><i class="fa fa-download fa-sm"></i> file download</a>
	{% else %}
	    Pending.. 
	{% endif %}</td>
	<td>{{result.uploaded_at}}</td>
	<td>{{result.files_generation_time}}</td>
    <td nowrap>{{ result.user_created }}</td>
{% endblock listboard_table_columns %}

trainee_export/templates/trainee_export/non_crf_export.html
<div class="panel panel-default panel-table">
    <div class="panel-heading">
      <div class="row">
        <div class="col col-xs-6">
          <h3 class="panel-title">Non CRF Data Export</h3>
        </div>
        <div class="col col-xs-6 text-right">
            <a id="download_td_files" title="Generate all Export" class="btn btn-sm btn-primary btn-download" role="button" 
              href="{% url 'trainee_export:home_url' %}?download=2">
                  <i class="fa fa-plus fa-sm"></i> Generate Export
          </a>
        </div>
      </div>
    </div>
    <div class="panel-body">
       {% if non_crf_exports %}
      <table id="non_crf_export" class="table table-striped table-bordered table-list">
          <thead>
              <tr>
                  <th>Export identifier</th>
                  <th>Document</th>
                  <th>Report data range</th>
                  <th>Datetime generated</th>
              </tr>
          </thead>
          <tfoot>
              <tr>
                  <th>Export identifier</th>
                  <th>Document</th>
                  <th>Report data range</th>
                  <th>Datetime generated</th>
              </tr>
          </tfoot>
          <tbody>
          {% for non_crf_download in non_crf_exports %}
              <tr>
                  <td>{{ non_crf_download.export_identifier }}</td>
                  <td>{% if non_crf_download.doc_url %}
                     <a href={{ non_crf_download.doc_url }}><i class="fa fa-download fa-sm"></i> file download</a>
                  {% else %}
                      Pending.. 
                  {% endif %}</td>
                   <td>{{ non_crf_download.start_date }} - {{ non_crf_download.end_date }}</td>
                   <td>{{ non_crf_download.uploaded_at }}</td>
              </tr>
          {% endfor %}
          </tbody>
      </table>
      {% else %}
          <p>No generated files yet</p>
      {% endif %}
    </div>
  
  </div>

trainee_export/templates/trainee_export/subject_crf_export.html
<div class="panel panel-default panel-table">
    <div class="panel-heading">
      <div class="row">
        <div class="col col-xs-6">
          <h3 class="panel-title">Subject CRF Data Export</h3>
        </div>
        <div class="col col-xs-6 text-right">
            <a id="download_td_files" title="Generate all Export" class="btn btn-sm btn-primary btn-download" role="button" 
              href="{% url 'trainee_export:home_url' %}?download=3">
                  <i class="fa fa-plus fa-sm"></i> Generate Export
          </a>
        </div>
      </div>
    </div>
    <div class="panel-body">
       {% if subject_crf_exports %}
      <table id="non_crf_export" class="table table-striped table-bordered table-list">
          <thead>
              <tr>
                  <th>Export identifier</th>
                  <th>Document</th>
                  <th>Report data range</th>
                  <th>Datetime generated</th>
              </tr>
          </thead>
          <tfoot>
              <tr>
                  <th>Export identifier</th>
                  <th>Document</th>
                  <th>Report data range</th>
                  <th>Datetime generated</th>
              </tr>
          </tfoot>
          <tbody>
          {% for cg_crf_download in subject_crf_exports %}
              <tr>
                  <td>{{ cg_crf_download.export_identifier }}</td>
                  <td>{% if cg_crf_download.doc_url %}
                     <a href={{ cg_crf_download.doc_url }}><i class="fa fa-download fa-sm"></i> file download</a>
                  {% else %}
                      Pending.. 
                  {% endif %}</td>
                   <td>{{ cg_crf_download.start_date }} - {{ cg_crf_download.end_date }}</td>
                   <td>{{ cg_crf_download.uploaded_at }}</td>
              </tr>
          {% endfor %}
          </tbody>
      </table>
      {% else %}
          <p>No generated files yet</p>
      {% endif %}
    </div>
  
  </div>